#@data/values
---
system_domain: ""
system_namespace: ""
app_log_destinations: []

fluentd:
  prometheus:
    path: '/metrics'
    port: '24231'

images:
  log_cache: ""
  syslog_server: ""
  log_cache_gateway: ""
  fluent: ""
  cf_auth_proxy: ""

debug: false

log_cache_api_replicas: 2
log_cache_replicas: 6
